version: "3.9"

services:

  collector:
    build: ./collector
    container_name: collector-1
    ports:
      - "5000:5000"
    networks:
      - monitor-net

  edge-node-a:
    build: ./agent
    container_name: edge-node-a-1
    environment:
      NODE_NAME: edge-node-a
      NODE_ROLE: edge
      COLLECTOR_URL: http://collector:5000/report
      WINDOW_SIZE: "2"
    mem_limit: 128m
    cpus: 0.5
    depends_on:
      - collector
    networks:
      - monitor-net

  edge-node-b:
    build: ./agent
    container_name: edge-node-b-1
    environment:
      NODE_NAME: edge-node-b
      NODE_ROLE: edge
      COLLECTOR_URL: http://collector:5000/report
      WINDOW_SIZE: "2"
    mem_limit: 128m
    cpus: 0.5
    depends_on:
      - collector
    networks:
      - monitor-net

  core-node:
    build: ./agent
    container_name: core-node-1
    environment:
      NODE_NAME: core-node
      NODE_ROLE: core
      COLLECTOR_URL: http://collector:5000/report
      WINDOW_SIZE: "2"
    mem_limit: 256m
    cpus: 1.0
    depends_on:
      - collector
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
